name: "tagged_release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install brainstat.
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
    
    - name: Build binary wheel and tarball.
      run: |
        python -m build --sdist --wheel --outdir dist/
    
    - name: Publish to PyPi test.
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/